parameters:
#    acmen_hello.example.class: Acme\HelloBundle\Example

services:
#    acmen_hello.example:
#        class: %acmen_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
